/*
 * Copyright (c) 2014 All Rights Reserved.
 */
package test.model;

// auto generated imports
import java.util.Date;

/**
 * A data object class directly models database table <tt>tts_product</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tts_product.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author dalgen
 */
public class TtsProductDto {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */

	private Long id;


	/**
	 * This property corresponds to db column <tt>pid</tt>.
	 */

	private Long pid;


	/**
	 * This property corresponds to db column <tt>source_id</tt>.
	 */

	private Long sourceId;


	/**
	 * This property corresponds to db column <tt>cid</tt>.
	 */

	private Integer cid;


	/**
	 * This property corresponds to db column <tt>website</tt>.
	 */

	private Integer website;


	/**
	 * This property corresponds to db column <tt>is_index</tt>.
	 */

	private Integer isIndex;


	/**
	 * This property corresponds to db column <tt>is_mobile_top</tt>.
	 */

	private Integer isMobileTop;


	/**
	 * This property corresponds to db column <tt>order_id</tt>.
	 */

	private Integer orderId;


	/**
	 * This property corresponds to db column <tt>random_id</tt>.
	 */

	private Integer randomId;


	/**
	 * This property corresponds to db column <tt>price</tt>.
	 */

	private Integer price;


	/**
	 * This property corresponds to db column <tt>sales</tt>.
	 */

	private Integer sales;


	/**
	 * This property corresponds to db column <tt>create_time</tt>.
	 */

	private Date createTime;


	/**
	 * This property corresponds to db column <tt>modify_time</tt>.
	 */

	private Date modifyTime;


	/**
	 * This property corresponds to db column <tt>publish_user_id</tt>.
	 */

	private Integer publishUserId;


	/**
	 * This property corresponds to db column <tt>modify_user_id</tt>.
	 */

	private Integer modifyUserId;


	/**
	 * This property corresponds to db column <tt>is_deleted</tt>.
	 */

	private Integer isDeleted;


	/**
	 * This property corresponds to db column <tt>deleted_type</tt>.
	 */

	private Integer deletedType;


	/**
	 * This property corresponds to db column <tt>leaf_cate_id</tt>.
	 */

	private Integer leafCateId;


	/**
	 * This property corresponds to db column <tt>is_mobile_display</tt>.
	 */

	private Integer isMobileDisplay;


	/**
	 * This property corresponds to db column <tt>online_time</tt>.
	 */

	private Date onlineTime;


	/**
	 * This property corresponds to db column <tt>description</tt>.
	 */

	private String description;


	/**
	 * This property corresponds to db column <tt>url</tt>.
	 */

	private String url;


    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public Long getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(Long id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>pid</tt>.
     *
     * @return property value of pid
     */
	public Long getPid() {
		return pid;
	}
	
	/**
	 * Setter method for property <tt>pid</tt>.
	 * 
	 * @param pid value to be assigned to property pid
     */
	public void setPid(Long pid) {
		this.pid = pid;
	}

    /**
     * Getter method for property <tt>sourceId</tt>.
     *
     * @return property value of sourceId
     */
	public Long getSourceId() {
		return sourceId;
	}
	
	/**
	 * Setter method for property <tt>sourceId</tt>.
	 * 
	 * @param sourceId value to be assigned to property sourceId
     */
	public void setSourceId(Long sourceId) {
		this.sourceId = sourceId;
	}

    /**
     * Getter method for property <tt>cid</tt>.
     *
     * @return property value of cid
     */
	public Integer getCid() {
		return cid;
	}
	
	/**
	 * Setter method for property <tt>cid</tt>.
	 * 
	 * @param cid value to be assigned to property cid
     */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

    /**
     * Getter method for property <tt>website</tt>.
     *
     * @return property value of website
     */
	public Integer getWebsite() {
		return website;
	}
	
	/**
	 * Setter method for property <tt>website</tt>.
	 * 
	 * @param website value to be assigned to property website
     */
	public void setWebsite(Integer website) {
		this.website = website;
	}

    /**
     * Getter method for property <tt>isIndex</tt>.
     *
     * @return property value of isIndex
     */
	public Integer getIsIndex() {
		return isIndex;
	}
	
	/**
	 * Setter method for property <tt>isIndex</tt>.
	 * 
	 * @param isIndex value to be assigned to property isIndex
     */
	public void setIsIndex(Integer isIndex) {
		this.isIndex = isIndex;
	}

    /**
     * Getter method for property <tt>isMobileTop</tt>.
     *
     * @return property value of isMobileTop
     */
	public Integer getIsMobileTop() {
		return isMobileTop;
	}
	
	/**
	 * Setter method for property <tt>isMobileTop</tt>.
	 * 
	 * @param isMobileTop value to be assigned to property isMobileTop
     */
	public void setIsMobileTop(Integer isMobileTop) {
		this.isMobileTop = isMobileTop;
	}

    /**
     * Getter method for property <tt>orderId</tt>.
     *
     * @return property value of orderId
     */
	public Integer getOrderId() {
		return orderId;
	}
	
	/**
	 * Setter method for property <tt>orderId</tt>.
	 * 
	 * @param orderId value to be assigned to property orderId
     */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

    /**
     * Getter method for property <tt>randomId</tt>.
     *
     * @return property value of randomId
     */
	public Integer getRandomId() {
		return randomId;
	}
	
	/**
	 * Setter method for property <tt>randomId</tt>.
	 * 
	 * @param randomId value to be assigned to property randomId
     */
	public void setRandomId(Integer randomId) {
		this.randomId = randomId;
	}

    /**
     * Getter method for property <tt>price</tt>.
     *
     * @return property value of price
     */
	public Integer getPrice() {
		return price;
	}
	
	/**
	 * Setter method for property <tt>price</tt>.
	 * 
	 * @param price value to be assigned to property price
     */
	public void setPrice(Integer price) {
		this.price = price;
	}

    /**
     * Getter method for property <tt>sales</tt>.
     *
     * @return property value of sales
     */
	public Integer getSales() {
		return sales;
	}
	
	/**
	 * Setter method for property <tt>sales</tt>.
	 * 
	 * @param sales value to be assigned to property sales
     */
	public void setSales(Integer sales) {
		this.sales = sales;
	}

    /**
     * Getter method for property <tt>createTime</tt>.
     *
     * @return property value of createTime
     */
	public Date getCreateTime() {
		return createTime;
	}
	
	/**
	 * Setter method for property <tt>createTime</tt>.
	 * 
	 * @param createTime value to be assigned to property createTime
     */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

    /**
     * Getter method for property <tt>modifyTime</tt>.
     *
     * @return property value of modifyTime
     */
	public Date getModifyTime() {
		return modifyTime;
	}
	
	/**
	 * Setter method for property <tt>modifyTime</tt>.
	 * 
	 * @param modifyTime value to be assigned to property modifyTime
     */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

    /**
     * Getter method for property <tt>publishUserId</tt>.
     *
     * @return property value of publishUserId
     */
	public Integer getPublishUserId() {
		return publishUserId;
	}
	
	/**
	 * Setter method for property <tt>publishUserId</tt>.
	 * 
	 * @param publishUserId value to be assigned to property publishUserId
     */
	public void setPublishUserId(Integer publishUserId) {
		this.publishUserId = publishUserId;
	}

    /**
     * Getter method for property <tt>modifyUserId</tt>.
     *
     * @return property value of modifyUserId
     */
	public Integer getModifyUserId() {
		return modifyUserId;
	}
	
	/**
	 * Setter method for property <tt>modifyUserId</tt>.
	 * 
	 * @param modifyUserId value to be assigned to property modifyUserId
     */
	public void setModifyUserId(Integer modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

    /**
     * Getter method for property <tt>isDeleted</tt>.
     *
     * @return property value of isDeleted
     */
	public Integer getIsDeleted() {
		return isDeleted;
	}
	
	/**
	 * Setter method for property <tt>isDeleted</tt>.
	 * 
	 * @param isDeleted value to be assigned to property isDeleted
     */
	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

    /**
     * Getter method for property <tt>deletedType</tt>.
     *
     * @return property value of deletedType
     */
	public Integer getDeletedType() {
		return deletedType;
	}
	
	/**
	 * Setter method for property <tt>deletedType</tt>.
	 * 
	 * @param deletedType value to be assigned to property deletedType
     */
	public void setDeletedType(Integer deletedType) {
		this.deletedType = deletedType;
	}

    /**
     * Getter method for property <tt>leafCateId</tt>.
     *
     * @return property value of leafCateId
     */
	public Integer getLeafCateId() {
		return leafCateId;
	}
	
	/**
	 * Setter method for property <tt>leafCateId</tt>.
	 * 
	 * @param leafCateId value to be assigned to property leafCateId
     */
	public void setLeafCateId(Integer leafCateId) {
		this.leafCateId = leafCateId;
	}

    /**
     * Getter method for property <tt>isMobileDisplay</tt>.
     *
     * @return property value of isMobileDisplay
     */
	public Integer getIsMobileDisplay() {
		return isMobileDisplay;
	}
	
	/**
	 * Setter method for property <tt>isMobileDisplay</tt>.
	 * 
	 * @param isMobileDisplay value to be assigned to property isMobileDisplay
     */
	public void setIsMobileDisplay(Integer isMobileDisplay) {
		this.isMobileDisplay = isMobileDisplay;
	}

    /**
     * Getter method for property <tt>onlineTime</tt>.
     *
     * @return property value of onlineTime
     */
	public Date getOnlineTime() {
		return onlineTime;
	}
	
	/**
	 * Setter method for property <tt>onlineTime</tt>.
	 * 
	 * @param onlineTime value to be assigned to property onlineTime
     */
	public void setOnlineTime(Date onlineTime) {
		this.onlineTime = onlineTime;
	}

    /**
     * Getter method for property <tt>description</tt>.
     *
     * @return property value of description
     */
	public String getDescription() {
		return description;
	}
	
	/**
	 * Setter method for property <tt>description</tt>.
	 * 
	 * @param description value to be assigned to property description
     */
	public void setDescription(String description) {
		this.description = description;
	}

    /**
     * Getter method for property <tt>url</tt>.
     *
     * @return property value of url
     */
	public String getUrl() {
		return url;
	}
	
	/**
	 * Setter method for property <tt>url</tt>.
	 * 
	 * @param url value to be assigned to property url
     */
	public void setUrl(String url) {
		this.url = url;
	}
}
