/*
 * Copyright (c) 2014 All Rights Reserved.
 */
package test.dao.impl;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import test.dao.TtsProductDao;
import org.springframework.stereotype.Service;
// auto generated imports
import test.model.TtsProductDto;
import java.util.List;
import org.springframework.dao.DataAccessException;
import test.model.TtsProductDto;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>test.dao.TtsProductDao</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/tts_product.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author dalgen
 */
@Service("TtsProductDao")
public class TtsProductDaoImpl extends SqlMapClientDaoSupport implements TtsProductDao {

	private static final String namespace="TtsProduct.";

	/**
	 *  Query DB table <tt>tts_product</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from tts_product</tt>
	 *
	 *	@return TtsProductDto
	 *	@throws DataAccessException
	 */	 
    public TtsProductDto getTest() throws DataAccessException {

        return (TtsProductDto) getSqlMapClientTemplate().queryForObject(namespace+"MS-TTS-PRODUCT-GET-TEST", null);

    }

	/**
	 *  Insert one <tt>TtsProductDto</tt> object to DB table <tt>tts_product</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into tts_product(pid,source_id,cid,website,is_index,is_mobile_top,price,sales,create_time,modify_time,publish_user_id,modify_user_id,is_deleted,order_id,leaf_cate_id,online_time,description,url) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param ttsProduct
	 *	@return Long
	 *	@throws DataAccessException
	 */	 
    public Long insert(TtsProductDto ttsProduct) throws DataAccessException {
    	if (ttsProduct == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert(namespace+"MS-TTS-PRODUCT-INSERT", ttsProduct);

        return ttsProduct.getId();
    }

	/**
	 *  Update DB table <tt>tts_product</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update tts_product set random_id=? where (id = ?)</tt>
	 *
	 *	@param randomId
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateRandomId(Integer randomId, Long id) throws DataAccessException {
        Map param = new HashMap();

        param.put("randomId", randomId);
        param.put("id", id);

        return getSqlMapClientTemplate().update(namespace+"MS-TTS-PRODUCT-UPDATE-RANDOM-ID", param);
    }

	/**
	 *  Query DB table <tt>tts_product</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, pid, source_id, cid, website, is_index, is_mobile_top, order_id, price, sales, create_time, modify_time, publish_user_id, modify_user_id, is_deleted, leaf_cate_id, is_mobile_display, online_time, description, url from tts_product where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return TtsProductDto
	 *	@throws DataAccessException
	 */	 
    public TtsProductDto getById(Long id) throws DataAccessException {

        return (TtsProductDto) getSqlMapClientTemplate().queryForObject(namespace+"MS-TTS-PRODUCT-GET-BY-ID", id);

    }

	/**
	 *  Query DB table <tt>tts_product</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, pid, source_id, cid, website, is_index, is_mobile_top, order_id, price, sales, create_time, modify_time, publish_user_id, modify_user_id, is_deleted, leaf_cate_id, is_mobile_display, online_time, description, url from tts_product where (source_id = ?)</tt>
	 *
	 *	@param sourceId
	 *	@return TtsProductDto
	 *	@throws DataAccessException
	 */	 
    public TtsProductDto getBySourceId(Long sourceId) throws DataAccessException {

        return (TtsProductDto) getSqlMapClientTemplate().queryForObject(namespace+"MS-TTS-PRODUCT-GET-BY-SOURCE-ID", sourceId);

    }

	/**
	 *  Update DB table <tt>tts_product</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update tts_product set is_deleted=1</tt>
	 *
	 *	@param ids
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateBatch(String ids) throws DataAccessException {

        return getSqlMapClientTemplate().update(namespace+"MS-TTS-PRODUCT-UPDATE-BATCH", ids);
    }

	/**
	 *  Update DB table <tt>tts_product</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update tts_product set is_deleted=? where ((pid = ?) AND (id = ?))</tt>
	 *
	 *	@param isDeleted
	 *	@param pid
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteProduct(Integer isDeleted, Long pid, Long id) throws DataAccessException {
        Map param = new HashMap();

        param.put("isDeleted", isDeleted);
        param.put("pid", pid);
        param.put("id", id);

        return getSqlMapClientTemplate().update(namespace+"MS-TTS-PRODUCT-DELETE-PRODUCT", param);
    }

	/**
	 *  Query DB table <tt>tts_product</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, pid, source_id, cid, website, is_index, is_mobile_top, order_id, price, sales, create_time, modify_time, publish_user_id, modify_user_id, is_deleted, leaf_cate_id, is_mobile_display, online_time, description, url from tts_product where (pid = ?)</tt>
	 *
	 *	@param pid
	 *	@return TtsProductDto
	 *	@throws DataAccessException
	 */	 
    public TtsProductDto selectByPid(Long pid) throws DataAccessException {

        return (TtsProductDto) getSqlMapClientTemplate().queryForObject(namespace+"MS-TTS-PRODUCT-SELECT-BY-PID", pid);

    }

	/**
	 *  Query DB table <tt>tts_product</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from tts_product</tt>
	 *
	 *	@return Integer
	 *	@throws DataAccessException
	 */	 
    public Integer selectCount() throws DataAccessException {

        return (Integer) getSqlMapClientTemplate().queryForObject(namespace+"MS-TTS-PRODUCT-SELECT-COUNT", null);

    }

	/**
	 *  Delete records from DB table <tt>tts_product</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from tts_product where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(Long id) throws DataAccessException {

        return getSqlMapClientTemplate().delete(namespace+"MS-TTS-PRODUCT-DELETE-BY-ID", id);
    }

	/**
	 *  Update DB table <tt>tts_product</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update tts_product set is_index=?, is_mobile_top=?, leaf_cate_id=?, order_id=?, online_time=?, description=?, modify_user_id=?, url=?, modify_time=? where (id = ?)</tt>
	 *
	 *	@param ttsProduct
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateById(TtsProductDto ttsProduct) throws DataAccessException {
    	if (ttsProduct == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update(namespace+"MS-TTS-PRODUCT-UPDATE-BY-ID", ttsProduct);
    }

	/**
	 *  Query DB table <tt>tts_product</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select t.id, t.pid, t.source_id, t.cid, t.website, t.is_index, t.is_mobile_top, t.order_id, t.price, t.sales, t.create_time, t.modify_time, t.publish_user_id, t.modify_user_id, t.is_deleted, t.leaf_cate_id, t.is_mobile_display, t.online_time, t.description, t.url from tts_product t</tt>
	 *
	 *	@param tagId
	 *	@return List<TtsProductDto>
	 *	@throws DataAccessException
	 */	 
    public List<TtsProductDto> selectByTagId(String tagId) throws DataAccessException {

        return getSqlMapClientTemplate().queryForList(namespace+"MS-TTS-PRODUCT-SELECT-BY-TAG-ID", tagId);

    }

}